repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff
      # the excluded files have errors that I can't deal with right now
        exclude: |
          (?x)^scripts/(printable_image[^\.]+|download_and_upload_images|fix_borders_gcs|prepare_card_for_printing_stretch).py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
